[CU-383uux9] Initial routing
Entropy1729/aleo_wallet pull request #7
Opened 2022-08-03 16:40 UTC by manucamejo

2022-08-03 19:23 UTC, mationorato requested changes

2022-08-03 19:23 UTC, mationorato commented on front/src/App.res
> +      | list{"create-login"} => <CreateLogin />
we should not use - in the routes. If you are trying to infer a nested route, something like `list{"create","login"}` should be used instead, representing `/create/login` (which is not a correct path syntax, but that's another discussion)

2022-08-03 20:59 UTC, manucamejo commented on front/src/App.res
> +      | list{"create-login"} => <CreateLogin />
I've changed the route `create-login` to `singin`

2022-08-04 14:20 UTC, mationorato approved these changes
great!

2022-08-04 14:20 UTC, merged