Endpoint file
Entropy1729/aleo_wallet pull request #8
Opened 2022-08-03 17:00 UTC by manucamejo

2022-08-03 19:17 UTC, mationorato requested changes

2022-08-03 19:17 UTC, mationorato commented on front/src/utils/Endpoint.res
> +@val @scope(("process", "env")) external _aleo_host: option<string> = "REACT_APP_ALEO_HOST"
We should name this REACT_APP_WALLET_API_HOST.

ALEO_HOST sound more like the RPC or something for the ledger

2022-08-04 14:50 UTC, manucamejo commented on front/src/utils/Endpoint.res
> +@val @scope(("process", "env")) external _aleo_host: option<string> = "REACT_APP_ALEO_HOST"
Thanks, corrected.

2022-08-04 15:41 UTC, mationorato approved these changes
nice

2022-08-04 15:41 UTC, merged